### ISSUE TITLE
There is no reference having Cloud Manager installed as a requirement for Cloud Sync.

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/cloud-manager-sync#30]
Page: [Quick start for Cloud Sync](https://docs.netapp.com/us-en/cloud-manager-sync/task-quick-start.html)

**Comment by netapp-bcammett** [comment]
@virtualhawk,
Do you mean a requirement for logging in to Cloud Manager? There's nothing that a customer needs to install for Cloud Sync (other than a data broker).

**Comment by virtualhawk** [comment]
Hi Ben,

               To add working environments to Cloud Manager, if I recall correctly, you need to have a connector installed.  So if you want to add CVO or On-Prem clusters as either a source or target, you would need a connector.

Thanks,

David Hawkins
Professional Services Consultant
Global Services Solutions Center

NetApp
+1 330.892.7057 Direct Phone
***@***.******@***.***>

Upcoming Out of the office: September 2nd - 5th

**Comment by netapp-bcammett** [comment]
David,

Yes, to sync data to or from some source or target locations, you will need a working environment. We have that documented when setting up a sync relationship:

> Create sync relationships for specific types of working environments

> If you want to create sync relationships for any of the following, then you first need to create or discover the working environment:
> 
> * Amazon FSx for ONTAP
> * Azure NetApp Files
> * Cloud Volumes ONTAP
> * On-prem ONTAP clusters

We then link to the docs that describe how to create those working environments (which includes the Connector requirement).

But a working environment (and Connector) isn't a requirement for all supported storage locations (for example, an NFS server, S3 bucket, etc.).

Would it help if the "Get started" section mentioned the working environment + Connector requirement up-front, rather than just right before you create your first sync relationship? 

Thanks,
Ben

**Comment by virtualhawk** [comment]
Hi Ben,

               Totally agree about it not being required for some scenarios.  Personally, I think it should be mentioned in the "Getting Started" page for specific working environments, i.e CVO, On-Prem ONTAP Clusters, etc. A connector is required so there is no confusion for customers.

Thanks,

David Hawkins
Professional Services Consultant
Global Services Solutions Center

NetApp
+1 330.892.7057 Direct Phone
***@***.******@***.***>

Upcoming Out of the office: September 2nd - 5th

**Comment by netapp-bcammett** [comment]
David,

I agree, that makes sense. I'll add those details and let you know when it's done.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@virtualhawk,

I added a new step for logging in and setting up Cloud Manager.
https://docs.netapp.com/us-en/cloud-manager-sync/task-quick-start.html

Please let me know if you have any additional feedback.

Thanks again,
Ben
